version: '3'

services:
  database:
    image: mariadb:${MARIADB_VERSION:-10.4.31}-focal
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
    volumes:
      - database_data:/var/lib/mysql:rw

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database
    ports:
      - "8080:80" # Vous pouvez changer le port si nécessaire
    environment:
      PMA_HOST: database
      PMA_PORT: 3306 # Port par défaut de MariaDB
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}

volumes:
  database_data: